- client/package-lock.json
- client/package.json
- client/public/manifest.json
- client/src/components/container/Root.js
- client/src/components/page/About.js
- client/src/components/page/Home.js
- client/src/components/ui/CustomNavBar.js
- client/src/components/ui/TeamIntroCard.js
- client/src/constants/links.js
- client/src/constants/webCodes.js
- client/src/index.css
- client/src/index.js
- client/src/reducers/contributors.js
- client/src/reducers/root.js
- client/src/reducers/user.js
- server/pom.xml
- server/src/main/java/com/google/codeu/servlets/LoginServlet.java
- server/src/main/java/com/google/codeu/servlets/LoginStatusServlet.java
- server/src/main/java/com/google/codeu/servlets/LogoutServlet.java
- server/src/main/webapp/WEB-INF/appengine-web.xml
- shared/user.proto
Trying to match the codebase: https://github.com/google/codeu-starter-project
> Refactored the codebase to more accurately match the codeu starter

- client/package-lock.json
- client/src/reducers/contributors.js
Added name (Alex Kim) and description to the second slot of the about page
> Added name and description to contributors.js

- client/src/reducers/contributors.js
Our javascript formatter, prettier io, doesn't format long strings properly so I manually reformatted it to 80 line character count.
No changes to the final rendered output.
Screenshot:
> Reformat Alex's string description to fit 80 character count.

- README.md
Issue: NONE
PR: https://github.com/fluffysheep-codeu/Summer2019-Team30/pull/31
> Update README.md with our team name.

- server/src/main/java/com/google/codeu/filters/SinglePageAppFilter.java
- tools/format-java.sh
Declared the correct package in SinglePageAppFilter.java 
Formatted java files for google
> Fixing Bug in SinglePageAppFilter

- server/src/main/java/com/google/codeu/data/Datastore.java
Function will return the total number of messages from all users
> Added getTotalMessageCount() to Datastore.java

- client/src/components/ui/CustomNavBar.js
- client/src/constants/links.js
- client/src/reducers/contributors.js
- server/src/main/java/com/google/codeu/data/Datastore.java
- server/src/main/java/com/google/codeu/servlets/StatsPageServlet.java
- server/src/main/java/com/google/codeu/servlets/UserListServlet.java
Added function to Datastore.java to get a list of all users and added the function to the UserList servlet
> Community Page Displays Blank List of Users

- client/package-lock.json
- client/src/components/container/Root.js
- client/src/components/page/StatsPage.js
- client/src/constants/links.js
- package-lock.json
- server/src/main/java/com/google/codeu/servlets/StatsPageServlet.java
> Clicking on Stats link prints hello world and opens the Stats page

- client/src/components/page/StatsPage.js
- server/src/main/java/com/google/codeu/servlets/StatsPageServlet.java
> Stats page now displays the number of messages on the site

- client/src/components/page/StatsPage.js
I forgot to push the changes after I committed them and I merged.
Issue: #16
PR: #58
> Took the curly braces out of the message string for the stats page

- client/src/components/container/Root.js
- client/src/components/page/CommunityPage.js
- client/src/components/ui/UserItem.js
- client/src/constants/links.js
- server/src/main/java/com/google/codeu/data/Datastore.java
- server/src/main/java/com/google/codeu/servlets/StatsPageServlet.java
- server/src/main/java/com/google/codeu/servlets/UserListServlet.java
> Creating community page to display every user that has sent a message.

- client/src/components/container/Root.js
- client/src/components/page/CommunityPage.js
- client/src/components/page/StatsPage.js
- client/src/components/ui/UserItem.js
- client/src/constants/links.js
- server/src/main/java/com/google/codeu/data/Datastore.java
- server/src/main/java/com/google/codeu/servlets/StatsPageServlet.java
- server/src/main/java/com/google/codeu/servlets/UserListServlet.java
> Made changes on how the Stats page looks on StatsPage.js

- client/src/components/container/Root.js
- client/src/components/page/PublicFeed.js
- client/src/components/ui/CustomNavBar.js
- client/src/components/ui/Message.js
- client/src/constants/links.js
- server/src/main/java/com/google/codeu/data/Datastore.java
- server/src/main/java/com/google/codeu/servlets/MessageFeedServlet.java
Issue : https://github.com/fluffysheep-codeu/Summer2019-Team30/issues/10
PR:https://github.com/fluffysheep-codeu/Summer2019-Team30/pull/65
Added publicfeed.js to receive and display all messages by user and time and date.
Modified Datastore.java to handle receiving and send sending information.
> Added public feed to show all messages and users pt2

- client/package-lock.json
- server/src/main/java/com/google/codeu/data/Datastore.java
Fixed the old code that was merged with Anthony's merge
Issue: #15 
PR: #66
> Fixed the old code that was merged

- client/src/components/page/UserPage.js
- server/src/main/java/com/google/codeu/data/Datastore.java
- server/src/main/java/com/google/codeu/servlets/MessageFeedServlet.java
Messages on the UserPage display correctly.
Issue: NONE
PR: https://github.com/fluffysheep-codeu/Summer2019-Team30/pull/67
> Displays messages on the userpage correctly

- client/src/components/page/PublicFeed.js
- client/src/constants/links.js
- server/src/main/java/com/google/codeu/servlets/MarkersServlet.java
- server/src/main/java/com/google/codeu/servlets/RestaurantServlet.java
Plan to make a box in public feed to allow a user to enter in an address and display it on a google map. Also store it in datastore
Issue: https://github.com/fluffysheep-codeu/Summer2019-Team30/issues/38
PR: #79
> Added servlets for Markers and Restaurants

- server/package-lock.json
- server/src/main/java/com/google/codeu/servlets/RestaurantServlet.java
> Bug fix in Restaurant servlet

- client/src/components/page/UserPage.js
Making first changes to the UI of the user page
Issue: https://github.com/fluffysheep-codeu/Summer2019-Team30/issues/84
PR: https://github.com/fluffysheep-codeu/Summer2019-Team30/pull/97
> New User Page layout

- client/src/components/page/UserPage.js
- client/src/constants/links.js
- server/src/main/java/com/google/codeu/data/Datastore.java
- server/src/main/java/com/google/codeu/data/Restaurant.java
- server/src/main/java/com/google/codeu/data/User.java
- server/src/main/java/com/google/codeu/servlets/AboutMeServlet.java
- server/src/main/java/com/google/codeu/servlets/LoginServlet.java
- server/src/main/java/com/google/codeu/servlets/ProfilePicServlet.java
- server/src/main/java/com/google/codeu/servlets/ProfileUploadServlet.java
Added a spot for a user to upload a profile picture 
Issue:https://github.com/fluffysheep-codeu/Summer2019-Team30/issues/84
PR: https://github.com/fluffysheep-codeu/Summer2019-Team30/pull/99
> Adding feature for a user to upload a profile picture

- client/src/components/ui/Message.js
- client/src/css/index.css
issue: https://github.com/fluffysheep-codeu/Summer2019-Team30/issues/86
pr: #98
> Made the message feed into cards to start view post issue

- client/package-lock.json
- client/src/components/page/UserPage.js
- server/src/main/java/com/google/codeu/servlets/AboutMeServlet.java
Fixed a bug where if you submitted bolded, italic, etc text for your about me it would show up as plain text
Issue: https://github.com/fluffysheep-codeu/Summer2019-Team30/issues/84
PR: https://github.com/fluffysheep-codeu/Summer2019-Team30/pull/103
> Fixing ckeditor bug for about me

- client/src/components/page/PublicFeed.js
Added textfields instead of textboxes
Issue: #87 
PR: #107
> Public feed ui

- client/src/components/page/PublicFeed.js
- server/src/main/java/com/google/codeu/servlets/RestaurantServlet.java
If the user is signed in when they add a restaurant it will create a new post
Issue: #89 
PR: #108
> Restaurants to posts

- client/src/components/page/Home.js
- client/src/components/page/UserPage.js
Minor ui changes to the home page and fixed some spacing issues on the user page.
Issue: https://github.com/fluffysheep-codeu/Summer2019-Team30/issues/84
PR: https://github.com/fluffysheep-codeu/Summer2019-Team30/pull/106
> Adding styling to home page 

- client/src/components/page/PublicFeed.js
- client/src/components/page/UserPage.js
> Restaurants now update correctly
